name: build

on:
  schedule:
    - cron: "0 22 * * 1"
  push:
    branches:
      - main
      - feature/*
      - hotfix/*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.21
    steps:
      - uses: actions/checkout@v4
      - name: Tests ausführen
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.16.2
          go mod download
          swag init
          go test ./...

  build-push:
    if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v3

      - id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}

      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.REG_USER }}/text2qrcode:${{ steps.vars.outputs.tag }},${{ secrets.REG_USER }}/text2qrcode:latest
