name: release

on: 
  push:
    branches:
      - main

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
        image: golang:1.26@sha256:fcdb3e42c5544e9682a635771eac76a698b66de79b1b50ec5b9ce5c5f14ad775
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Tests ausführen
      run: |
        go install github.com/swaggo/swag/cmd/swag@v1.16.2
        go mod download
        swag init
        go test ./...

# ---

  tag-next-version:
    permissions:
      contents: write
    needs: test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_next_version.outputs.version }}
      hasNextVersion: ${{ steps.get_next_version.outputs.hasNextVersion }}
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        fetch-depth: '0'
    - name: Get next version
      id: get_next_version
      uses: thenativeweb/get-next-version@437de50a7e8f5a2e2a248476e99bb09bdd791b07 # main
      with:
        prefix: 'v'
    - name: Create tag
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
        git tag ${{ steps.get_next_version.outputs.version }}
        git push origin ${{ steps.get_next_version.outputs.version }}


  build-gh-release:
    permissions:
      contents: write
    needs: tag-next-version
    if: ${{ needs.tag-next-version.outputs.hasNextVersion == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: go vorbereiten
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      with:
        go-version: '1.26.2'
    - name: Vars setzen
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Build
      run: |
        mkdir -p release/assets
        go install github.com/swaggo/swag/cmd/swag@v1.16.2
        go mod download
        swag init
        
        GOOS=linux GOARCH=amd64 go build -o release/text2qrcode-linux-amd64
        tar cvfJ release/assets/text2qrcode-linux-amd64.tar.xz release/text2qrcode-linux-amd64

        GOOS=linux GOARCH=arm64 go build -o release/text2qrcode-linux-arm64
        tar cvfJ release/assets/text2qrcode-linux-arm64.tar.xz release/text2qrcode-linux-arm64

        GOOS=windows GOARCH=amd64 go build -o release/text2qrcode-windows-amd64.exe
        zip release/assets/text2qrcode-windows-amd64.zip release/text2qrcode-windows-amd64.exe

        GOOS=windows GOARCH=arm64 go build -o release/text2qrcode-windows-arm64.exe
        zip release/assets/text2qrcode-windows-arm64.zip release/text2qrcode-windows-arm64.exe

        GOOS=darwin GOARCH=amd64 go build -o release/text2qrcode-darwin-amd64
        tar cvfJ release/assets/text2qrcode-darwin-amd64.tar.xz release/text2qrcode-darwin-amd64

        GOOS=darwin GOARCH=arm64 go build -o release/text2qrcode-darwin-arm64
        tar cvfJ release/assets/text2qrcode-darwin-arm64.tar.xz release/text2qrcode-darwin-arm64

    - name: Github-Release erstellen
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
      with:
        artifacts: "release/assets/*"
        tag: ${{ needs.tag-next-version.outputs.version }}

        
  build-docker:
    permissions:
      contents: read
    needs: tag-next-version
    if: ${{ needs.tag-next-version.outputs.hasNextVersion == 'true' }}
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}

      - uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.REG_USER }}/text2qrcode:${{ steps.vars.outputs.tag }},${{ secrets.REG_USER }}/text2qrcode:latest
