name: release

on: 
  push:
    branches:
      - main

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
        image: golang:1.26@sha256:079e59808d2d252516e27e3f3a9c003740dee7f75e55aa71528766d52bcfc16a
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - name: Tests ausführen
      run: |
        go install github.com/swaggo/swag/cmd/swag@v1.16.2
        go mod download
        swag init
        go test ./...

# ---

  tag-next-version:
    permissions:
      contents: write
    needs: test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_next_version.outputs.version }}
      hasNextVersion: ${{ steps.get_next_version.outputs.hasNextVersion }}
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        fetch-depth: '0'
    - name: Get next version
      id: get_next_version
      uses: thenativeweb/get-next-version@7914838558689219caf7fa01501038383d2d6116 # main
      with:
        prefix: 'v'
    - name: Create tag
      if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
        git tag ${{ steps.get_next_version.outputs.version }}
        git push origin ${{ steps.get_next_version.outputs.version }}


  build-gh-release:
    permissions:
      contents: write
    needs: tag-next-version
    if: ${{ needs.tag-next-version.outputs.hasNextVersion == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - name: go vorbereiten
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      with:
        go-version: '1.26.5'
    - name: Vars setzen
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Build
      run: |
        mkdir -p release/assets
        go install github.com/swaggo/swag/cmd/swag@v1.16.2
        go mod download
        swag init
        
        GOOS=linux GOARCH=amd64 go build -o release/text2qrcode-linux-amd64
        tar cvfJ release/assets/text2qrcode-linux-amd64.tar.xz release/text2qrcode-linux-amd64

        GOOS=linux GOARCH=arm64 go build -o release/text2qrcode-linux-arm64
        tar cvfJ release/assets/text2qrcode-linux-arm64.tar.xz release/text2qrcode-linux-arm64

        GOOS=windows GOARCH=amd64 go build -o release/text2qrcode-windows-amd64.exe
        zip release/assets/text2qrcode-windows-amd64.zip release/text2qrcode-windows-amd64.exe

        GOOS=windows GOARCH=arm64 go build -o release/text2qrcode-windows-arm64.exe
        zip release/assets/text2qrcode-windows-arm64.zip release/text2qrcode-windows-arm64.exe

        GOOS=darwin GOARCH=amd64 go build -o release/text2qrcode-darwin-amd64
        tar cvfJ release/assets/text2qrcode-darwin-amd64.tar.xz release/text2qrcode-darwin-amd64

        GOOS=darwin GOARCH=arm64 go build -o release/text2qrcode-darwin-arm64
        tar cvfJ release/assets/text2qrcode-darwin-arm64.tar.xz release/text2qrcode-darwin-arm64

    - name: Github-Release erstellen
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1
      with:
        artifacts: "release/assets/*"
        tag: ${{ needs.tag-next-version.outputs.version }}

        
  build-docker:
    permissions:
      contents: read
    needs: tag-next-version
    if: ${{ needs.tag-next-version.outputs.hasNextVersion == 'true' }}
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4
      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
        with:
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASS }}

      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.REG_USER }}/text2qrcode:${{ steps.vars.outputs.tag }},${{ secrets.REG_USER }}/text2qrcode:latest
