name: test

on:
  push:
    branches:
      - feature/*
      - hotfix/*
  pull_request:

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: golang:1.26@sha256:c42e4d75186af6a44eb4159dcfac758ef1c05a7011a0052fe8a8df016d8e8fb9
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Tests ausführen
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.16.2
          go mod download
          swag init
          go test ./...
