name: test

on:
  push:
    branches:
      - feature/*
      - hotfix/*
  pull_request:

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: golang:1.26@sha256:b75179794e029c128d4496f695325a4c23b29986574ad13dd52a0d3ee9f72a6f
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Tests ausführen
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.16.2
          go mod download
          swag init
          go test ./...
