name: test

on:
  push:
    branches:
      - feature/*
      - hotfix/*
  pull_request:

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: golang:1.26@sha256:32c0e6e5c4f6707717051091b4d0b077464a679eaab563e11474efc5328e2aa5
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Tests ausführen
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.16.2
          go mod download
          swag init
          go test ./...
